### ISSUE TITLE
vite and route with path parameter value contains a dot

### ISSUE THREAD

**Issue by spaceman2023** [mefechoel/svelte-navigator#104]
When you have a route with a path parameter you won't be able to navigate to the route if your path parameter value contains a dot.
In the readme there is a reference for sirv, but I use vite. Who can help me to solve the problem?

**Comment by mefechoel** [comment]
Yes, this is an issue with vite. You can try to work around that by url encoding the `"."` character with `"%2e"`.
Other than that please file an issue with vite if there isn't one already.
