### ISSUE TITLE
Is there any migration guide for Svelte-routing?

### ISSUE THREAD

**Issue by quantuminformation** [mefechoel/svelte-navigator#13]

**Comment by mefechoel** [comment]
There is no guide yet, but that's a great idea!

Theoretically you could just replace every import from 'svelte-routing' with 'svelte-navigator', and it should work, but I have not tested it.
The changes to the API are largely additive, so props, that work for svelte routing also work for svelte navigator.

I guess it would be nice to illustrate, in what way you could simplify your code by using svelte navigator, or which problems, that might occur with svelte routing, could be solved.

I'm thinking of giving an example on removing nested `Router`s in favour of nested `Route`s.
Or replacing calls to `navigate` with using the `useNavigate` hook, so one can take advantage of relative routing.

**Comment by quantuminformation** [comment]
ok mate, i'm not ready to switch yet, as i have an app in prod and have no issues with s routing, maybe emil will collab or smth.

**Comment by mefechoel** [comment]
Sure, if it works for you that's great! For basic routing needs svelte routing works really well; it's so widely used for a reason.
I had some issues with it, when I needed to host a page on a subroute and decided to dig deeper.

A big bonus for me is that you get a much more accessible routing experience out of the box.

I'd love to collaborate, if emil is up for it, but it seems that he is quite busy at the moment.

**Comment by quantuminformation** [comment]
tried this

![image](https://user-images.githubusercontent.com/216566/92592757-5f8d3400-f2a0-11ea-8a00-9889e0c669d7.png)
got this
![image](https://user-images.githubusercontent.com/216566/92592935-9a8f6780-f2a0-11ea-8535-38faf40096ca.png)

**Comment by mefechoel** [comment]
Hmm, that is not a very descriptive error message :D 

In the first picture, svelte-routings entry in package.json is highlighted. Could it be that it was replaced as well and your bundler now tries to get svelte-navigator version 1.4.2, which does not exist?

**Comment by quantuminformation** [comment]
yeah i fixed all that

**Comment by mefechoel** [comment]
Could you share the line from your `Profile.svelte` component? That seems to be where the error is coming from.

**Comment by quantuminformation** [comment]
![image](https://user-images.githubusercontent.com/216566/92600174-7be29e00-f2ab-11ea-87f4-ce5f9fe06392.png)

just here

![image](https://user-images.githubusercontent.com/216566/92600819-5609c900-f2ac-11ea-9e88-967e4be6f3c9.png)

**Comment by mefechoel** [comment]
Can you trace the error further? Somewhere, probably in the `routeLogic` function should be a call to some svelte-routing function, which does not work with svelte-navigator.

**Comment by quantuminformation** [comment]
error occurs before routlogic gets hit

**Comment by quantuminformation** [comment]
![image](https://user-images.githubusercontent.com/216566/92602721-cd405c80-f2ae-11ea-845d-cf8b958e6c81.png)
this is missing

**Comment by mefechoel** [comment]
Ok... That's a tough one...
What happens in the component rendering `Profile.svelte`? Svelte can apparently not instantiate it, so the error might come from the parent.
I'm gonna take a look at the `SvelteComponentDev` class. Maybe I can find where the target is getting lost...

**Comment by quantuminformation** [comment]
here is the code
```js
<script>
    import {
        getDBUserByUsername,
        getRelationshipRelativeToLoggedInUser,
        removeMentee,
        getKnowledgeGraph,
    } from "../backend"
    import { log } from "../util/logging"
    import DefaultSpinner from "../components/DefaultSpinner.svelte"
    import { userDataStore } from "../stores/userDataStore"
    import KnowledgeGraph from "../components/KnowledgeGraph.svelte"
    import {
        PENDING_MENTEE,
        MENTEE,
        MENTOR,
        CAN_ADD_AS_MENTEE,
        MAX_MENTEES,
        MAX_MENTORS,
    } from "../../sharedCode/clientConstants"
    import { profilePicURL } from "../util/profilepicurl"
    import AddMenteeDropDown from "../components/AddMenteeDropDown.svelte"

    let isOwnProfile
    export let profileUser
    export let username // comes from the route
    let myRelationshipToProfile // Relationship relative to the logged in user , can be MENTEE, PENDING_MENTEE or null
    let relationshipData

    $: {
        log(`username changed to ${username}`)
        routeLogic()
    }

    //  export let viewingAnonymously = !!firebase.auth().currentUser // not logged in //todo infuture decide if we want to allow this
    let promise

    /**
     * Calls even if profile route changes on profile route
     * See https://github.com/EmilTholin/svelte-routing/issues/151
     *
     *
     */
    function routeLogic() {
        isOwnProfile = false //default on route username change

        // check if user is current user
        if ($userDataStore && $userDataStore.username === username) {
            isOwnProfile = true
            profileUser = $userDataStore
            log(`Profile page for logged in user ${username}`)
        }
        log(`loading graph data for username ${username}`)

        const promiseWrap = async () => {
            if (!isOwnProfile) {
                //save a read here
                profileUser = await getDBUserByUsername(username)
                log(`got user ${profileUser}`)
            }
            if (!profileUser) {
                //user doesnt exist
                return false
            }
            const graph = await getKnowledgeGraph(profileUser.uid)
            log(`graph ${graph}`)
            // assigned to <knowlegegraph reactive var
            relationshipData = { userProfile: profileUser, ...graph }

            if ($userDataStore) {
                myRelationshipToProfile = await getRelationshipRelativeToLoggedInUser(
                    profileUser.uid
                )
                /*     if (!myRelationshipToProfile) {
                    //load the fields in case user wants to add as a mentee
                    // todo we might just need to render the select without the categories
                    categories = await getCategoriesAndStore()
                }*/
            }
            //isOwnProfile = false

            return true
        }

        promise = promiseWrap()
    }

    const unFollow = async (event) => {
        log(`unfollowing ${myRelationshipToProfile}`)

        if (myRelationshipToProfile === MENTEE) {
            var r = confirm(
                "Are you sure What to remove them as mentee? In order to add them back as a mentee, they will have to confirm again."
            )
            if (r == true) {
                let result = await removeMentee(profileUser)
                if (result) {
                    myRelationshipToProfile = undefined
                }
            } else {
                txt = "You pressed Cancel!"
            }
        } else {
            if (myRelationshipToProfile === PENDING_MENTEE) {
                let result = await removeMentee(profileUser)
                if (result) {
                    myRelationshipToProfile = undefined
                }
            }
        }
    }

    //1st time call on this route visit
    routeLogic()
</script>

<style>
    .graph-controls {
        position: absolute;
        top: 1vh;
        right: 1vh;
    }
    span.graph-controls {
        font-size: 0.8em;
    }
    .container {
        position: relative;
    }
</style>

<div class="container pt-1 px-3 mx-auto flex flex-wrap flex-col items-center">
    {#await promise}
        <DefaultSpinner />
        <!--todo can we get rid of result here as its no used?-->
    {:then result}
        {#if !result}
            <h1>Account does not exist</h1>
        {:else}
            <h1>{profileUser.displayName || 'User has not set a display name'}</h1>
            <h1>{profileUser.headline || 'User has not set a headline'}</h1>
            {#if isOwnProfile}<span>It's you!</span>{/if}
            {#if $userDataStore && !isOwnProfile}
                {#if myRelationshipToProfile === PENDING_MENTEE}
                    <p>
                        A request has been sent to {profileUser.displayName} for them to add you as a
                        mentee on their profile. Once this is confirmed by them, they will appear as
                        a mentee on your profile and you as a mentor on theirs.
                    </p>
                    <button
                        class="bg-white hover:bg-red-100 text-gray-800 font-semibold py-2 px-4
                            border bg-red-300 border-gray-400 rounded shadow"
                        on:click="{unFollow}">
                        Cancel request
                    </button>
                {:else if myRelationshipToProfile === MENTEE}
                    <button
                        title="Remove as mentee"
                        class="graph-controls bg-white hover:bg-red-100 text-gray-800 font-semibold
                            px-1 border border-gray-400 rounded shadow"
                        on:click="{unFollow}">
                        ❌ Remove Mentee
                    </button>
                {:else if myRelationshipToProfile === MENTOR}
                    <span
                        class="graph-controls"
                        title="This profile has reached the max amount of mentors">
                         ✅️ Your mentor!
                    </span>
                {:else if myRelationshipToProfile === CAN_ADD_AS_MENTEE}
                    <div class="graph-controls">
                        <AddMenteeDropDown
                            profileUser="{profileUser}"
                            bind:myRelationshipToProfile />
                    </div>
                {:else if myRelationshipToProfile === MAX_MENTEES}
                    <span class="graph-controls" title="You have reached the max amount of mentees">
                        ⚠️ Max Mentees
                    </span>
                {:else if myRelationshipToProfile === MAX_MENTORS}
                    <span
                        class="graph-controls"
                        title="This profile has reached the max amount of mentors">
                        ⚠️ Max Mentors
                    </span>
                {/if}
            {/if}
            <KnowledgeGraph data="{relationshipData}" />

            {#if profileUser.bio}
                <br />
                <h1 class="text-xl">Bio</h1>
                <p style=" white-space: pre-wrap; ">{profileUser.bio}</p>
            {/if}
            <br />
        {/if}
    {:catch error}
        <p style="color: red">error: {error}</p>
    {/await}
</div>
```

**Comment by quantuminformation** [comment]
Actually the error occurs on any route even index

**Comment by quantuminformation** [comment]
so on Home here:

![image](https://user-images.githubusercontent.com/216566/92627663-fc18fb80-f2cb-11ea-9e95-5abccd9cd286.png)

**Comment by mefechoel** [comment]
It seems really hard to find out where exactly this is coming from. I think I'll need to setup an app where I can reproduce this.

Have you found a simple setup you can reproduce this with?

**Comment by mefechoel** [comment]
I've got one more idea you could try... Maybe the bundler uses the packages main entry instead of the svelte entry. You can force it to use the svelte entry by changing the imports to "svelte-navigator/src/index.js".

**Comment by quantuminformation** [comment]
same error mate,

not sure how to reproduce mate, my repo is pretty big, could do a screen share if you like?

**Comment by mefechoel** [comment]
Yeah sure, that's probably easiest...
Can I contact you privatly somehow, so we can set a date?

**Comment by quantuminformation** [comment]
yeah dm me at nikos@mentorcv.com

thx

**Comment by mefechoel** [comment]
I tried to setup a small project, to reproduce the bug, and actually got the same error message... while still using `svelte-routing`.
Switching to `svelte-navigator` produced the same error:

![svnv-error](https://user-images.githubusercontent.com/25907978/93216033-7f709c00-f767-11ea-866e-1f745c35a326.png)

I'm starting to suspect, that this is not a problem with `svelte-navigator`, but with `vite-plugin-svelte` or probably with `svelte-hmr`. It's really hard to pinpoint where the error originates though...

If you have the time you could try to use rollup or webpack instead of vite, to see if it makes a difference. I'll probably try that myself when I find the time.

**Comment by mefechoel** [comment]
It seems as though it is somehow related to the usage of `<svelte:component this={component} />` in `Route.svelte`.

The error does not occur, when I use

```html
<Route path="/">
  <Home />
</Route>
```

instead of

```html
<Route path="/" component={Home} />
```

@quantuminformation If that fits your setup you can use this syntax for your routes.

**Comment by quantuminformation** [comment]
Thanks mate, will try soon.

@dominikg thought I'd send another one your way ;) https://github.com/mefechoel/svelte-navigator/issues/13#issuecomment-692712645

**Comment by quantuminformation** [comment]
Ok time to switch to your lib, svelte-routing breaks bigtime somehow

```js
Failed to init component
<Router>
Error: Function called outside component initialization
    at get_current_component (http://localhost:3000/@modules/svelte/internal/index.mjs:643:15)
    at getContext (http://localhost:3000/@modules/svelte/internal/index.mjs:676:12)
    at instance (http://localhost:3000/@modules/svelte-routing/src/Router.svelte?import:82:26)
    at init (http://localhost:3000/@modules/svelte/internal.js:1461:11)
    at new Router (http://localhost:3000/@modules/svelte-routing/src/Router.svelte?import:273:3)
    at createProxiedComponent (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:214:9)
    at new ProxyComponent (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:414:13)
    at new Proxy<Router> (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:472:11)
    at create_fragment (http://localhost:3000/src/App.svelte?import:389:11)
    at init (http://localhost:3000/@modules/svelte/internal.js:1476:37)
<App>
Error: Function called outside component initialization
    at get_current_component (http://localhost:3000/@modules/svelte/internal/index.mjs:643:15)
    at getContext (http://localhost:3000/@modules/svelte/internal/index.mjs:676:12)
    at instance (http://localhost:3000/@modules/svelte-routing/src/Router.svelte?import:82:26)
    at init (http://localhost:3000/@modules/svelte/internal.js:1461:11)
    at new Router (http://localhost:3000/@modules/svelte-routing/src/Router.svelte?import:273:3)
    at createProxiedComponent (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:214:9)
    at new ProxyComponent (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:414:13)
    at new Proxy<Router> (http://localhost:3000/@modules/svelte-hmr/runtime/hot-api-esm.js:472:11)
    at create_fragment (http://localhost:3000/src/App.svelte?import:389:11)
    at init (http://localhost:3000/@modules/svelte/internal.js:1476:37)```

**Comment by quantuminformation** [comment]
Ok done the upgrade 
![image](https://user-images.githubusercontent.com/216566/99075600-08fee780-25ba-11eb-8dfa-914eceba69b7.png)

but get the same error as above, so must be different issue

**Comment by mefechoel** [comment]
I suspect this is something in svelte-hmr or maybe svite. Have you updated svite recently? If so you could try to go back to a previous version and see if it works again. You could file a bug there if you find out more...

**Comment by quantuminformation** [comment]
tried `    hot: false` with svite, same issue

**Comment by mefechoel** [comment]
It looks suspiciously like the first error you were getting. I was able to work around that by changing the `<Route ... component={Comp} />` to `<Route ...><Comp /></Route>`. But again I think thee root of the error lies somewhere in svelte-hmr, although I have not tested it enough to know for sure or file an issue...

**Comment by quantuminformation** [comment]
In my project

![image](https://user-images.githubusercontent.com/216566/99155055-f3221d00-26b4-11eb-956e-7714efec0d06.png)

if I remove the router the app works fine

**Comment by quantuminformation** [comment]
Does this look like correct svite integration?


https://github.com/quantuminformation/my-first-svite-project

it doesnt render the route
![image](https://user-images.githubusercontent.com/216566/99155916-b1957000-26bc-11eb-9025-7acdefde97bd.png)

**Comment by quantuminformation** [comment]
Yeah its defo the router here messing with svite, I need to try an alternative router

**Comment by quantuminformation** [comment]
Issue fixed:
```
alias: {
    'svelte':'svelte/internal'
  }```
 
to vite.config.js

**Comment by dominikg** [comment]
svite-0.8.1 has been released which should work without the need to add the alias mentioned above.

**Comment by mefechoel** [comment]
Great, thanks @quantuminformation for the fix and @dominikg for the great work with svite!
I'll add a note to the readme just in case anyone else is having the same kind of issue.
