### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by mefechoel** [mefechoel/svelte-navigator#14]
With TypeScript now being a first class citizen in Svelte, Svelte Navigator should provide typings.

I don't think it's possible at the moment to write everything in TS, because that would require any project using Svelte Navigator to have the TS pre-processor set up as well.

There would need to be a way to strip type annotations from Svelte components and produce regular Svelte components and declaration files from it.

So to get things started, declaration files should be enough.

**Comment by mefechoel** [comment]
Added with 3.1.0

**Comment by quantuminformation** [comment]
nice
