### ISSUE TITLE
Conditional routes

### ISSUE THREAD

**Issue by quantuminformation** [mefechoel/svelte-navigator#27]
Is this something evil or can it be supported?
```
            {#if $userDataStore}
                <Route path="/" component="{Home}" />
            {:else}
                <Route path="/" component="{Feed}" />
            {/if}
```

**Comment by mefechoel** [comment]
This should just work... The Router runs the matching everytime the location or the registered routes change, so it's fine... Or does the example not work?

**Comment by quantuminformation** [comment]
wasnt working, ill double check tomorrow

**Comment by mefechoel** [comment]
Alright, I'll have to check to.
In the meantime you could do it like this:

```html
<Route path="/">
  {#if $userDataStore}
    <Home />
  {:else}
    <Feed />
  {/if}
</Route>
```

**Comment by mefechoel** [comment]
I could nor reproduce the issue... I've set up a small [example in the REPL](https://svelte.dev/repl/7a36b20e3a96400a9a7a1ddd9844c374?version=3.31.2), which uses both the `Route`'s `component` prop and the `Route` children for rendering the views and both work just fine... Could you provide an example where it does not work?

**Comment by quantuminformation** [comment]
<Route path="/">
  {#if $userDataStore}
    <Home />
  {:else}
    <Feed />
  {/if}
</Route>

works!

sorry i've been busy
