### ISSUE TITLE
visuallyHiddenStyle should include initial position to avoid visual bug

### ISSUE THREAD

**Issue by MirrorBytes** [mefechoel/svelte-navigator#28]
**Describe the bug** A clear and concise description of what the bug is.

`visuallyHiddenStyle` in `a11y.js` should include an initial position of `bottom: 0`. Without it, it renders under (or sometimes besides) elements in the `Router` causing scrollbars to appear.

**To Reproduce** Steps to reproduce the behavior:

1. Wrap a `div` with style of `height:100vh` with `Router`.
2. See scrollbar

Please add a link to an example in the Svelte REPL or in a Codesandbox, if you
can.

https://svelte.dev/repl/b4d98fdee025474291747a40a4ed32a7?version=3.31.2

**Expected behavior** A clear and concise description of what you expected to
happen.

No scrollbar or abnormal sizing issues.

**Comment by mefechoel** [comment]
Thanks for the detailed description and the suggested fix! I'll release a patch in the next days.

**Comment by MirrorBytes** [comment]
I'm use tailwind with resets. This still occurs due to the status bar being
a 1x1 element at the bottom or side of the screen.

**Comment by mefechoel** [comment]
Alright, good to know. I'll look into it further.

**Comment by MirrorBytes** [comment]
I have a feeling it's a bit of both here. In a vanilla environment it's the padding, but in a reset environment it's the status bar. I'll float with both for now and update this if I can find if there's something else going on

**Comment by mefechoel** [comment]
This should be fixed with 3.1.5. Please try if it works for you now.

**Comment by mefechoel** [comment]
Oh ok, missed the edit. It's probably still a good idea to move the status div off screen and out of the scrolling flow.
