### ISSUE TITLE
route guard

### ISSUE THREAD

**Issue by sysmat** [mefechoel/svelte-navigator#36]
**Is your feature request related to a problem? Please describe.** 

To have guarded some routes(admin, user, ...) something like angular router, so function which determines if the route can be activeted

**Describe the solution you'd like** 

```html
<script lang="ts">
function canActivate():boolean {
}
</script>
<Router {basepath}>
  <main>
    <Navbar />

    <Route path="queries" component={Queries}  />
    <Route path="statistics" component={Statistics} canActivate={canActivate}/>
    <Route path="status" component={Status} />
  </main>
</Router>

```

**Describe alternatives you've considered**

```html
<Router {basepath}>
  <main>
    <Navbar />

    <Route path="queries" component={Queries}  />
     {#if canActivate}
        <Route path="statistics" component={Statistics} />
     {/if}   
    <Route path="status" component={Status} />
  </main>
</Router>

```

**Comment by mefechoel** [comment]
Something very similar to what you're describing is already possible with a couple of helper components. Checkout the [private routes example](https://github.com/mefechoel/svelte-navigator/tree/main/example/private-routes) as a starting point. You could pass a check function and a redirect target (if you should need that) to the protected route as props.

I hope this works for your use case.
