### ISSUE TITLE
lazy loading & chunk bundles

### ISSUE THREAD

**Issue by sysmat** [mefechoel/svelte-navigator#37]
**Is your feature request related to a problem? Please describe.** 
- Some routes are accessible later so the component could be loaded as needed(something like angular) 
- So in that regards is it possible to have chunk bundles (like angular)

**Describe the solution you'd like** 

```html
<Router {basepath}>
  <main>
    <Navbar />

    <Route path="" component={Queries} />
    <Route path="queries" component={Queries} />
    <Route path="statistics" component={Statistics} lazy="true"/>
    <Route path="status" component={Status}  lazy="true"/>
  </main>
</Router>

```

**Comment by mefechoel** [comment]
This is also possible with the help of a few little helper components. Checkout the [lazy routes example](https://github.com/mefechoel/svelte-navigator/tree/main/example/lazy-loading) as a starting point.
Again, I don't think this should be part of the libraries api, as it is relatively straight forward to implement yourself and might be a burden on users who don't use the feature.
