### ISSUE TITLE
Can't go to the parent of parent route directly using navigate('/') i.e. from "/some/nestedpath" to "/"

### ISSUE THREAD

**Issue by inferno-umar** [mefechoel/svelte-navigator#62]
Error thrown is "Paused on promise rejection"
![err](https://user-images.githubusercontent.com/70754989/159406224-5d6bf800-c9a5-4a73-94ee-6b5e47123d27.png)

**Comment by inferno-umar** [comment]
Currently this worked for me
https://github.com/mefechoel/svelte-navigator/issues/52

But is it possible what I was doing at first ?

**Comment by mefechoel** [comment]
I'd need some more context to help you, but if I understand it correctly, you want to go to some url thats outside of the current route. If forbexample you're inside a `Route` with `path="/some/path"` and you want to go to `/`, you can do `navigate("../..")`. See the [`Link` documentation](https://github.com/mefechoel/svelte-navigator#link) for an example.
