### ISSUE TITLE
How to add progress bar before routing to next page

### ISSUE THREAD

**Issue by cnshu** [mefechoel/svelte-navigator#68]
labels : help wanted

I am beginner using `svelte-navigator` please can someone help me how can I add progress bar before loading the next and page.

**Comment by mefechoel** [comment]
Hello there, could you explain what exactly you want to do a bit more? Do you want to wait for some action to complete before navigating to another page or go to some page and then load something?

**Comment by cnshu** [comment]
just add loading animation while the next component is loading.

**Comment by mefechoel** [comment]
Have a look at the [lazy loading example](https://github.com/mefechoel/svelte-navigator/tree/main/example/lazy-loading). Maybe it helps with your use case.
