### ISSUE TITLE
Argument of type 'typeof Router' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'

### ISSUE THREAD

**Issue by Chunxei** [mefechoel/svelte-navigator#69]
**Describe the bug:**
Importing `Router` into my app gives the IDE error mentioned in the title. Importing any svelte component from `svelte-navigator` gives a similar error. The app runs despite the errors.

**To Reproduce:**
1. Import `Router` from `svelte-navigator`
2. place `<Router> ... </Router>` at app root
3. See editor error

**Expected behavior:**
To work as expected without any errors.

**Screenshots:**
<img width="769" alt="Screenshot 2022-04-26 at 06 56 21" src="https://user-images.githubusercontent.com/28638532/165231511-0aca4661-4471-412e-812e-82aa20f627a5.png">

**Desktop:**

- OS: macOS Monterey 12.1
- Browser: Brave
- Version: 1.37.113
- IDE: VS Code 1.66

**Comment by mefechoel** [comment]
Fixed with release of 3.1.6. Thanks for the PR!
