### ISSUE TITLE
export let path not working

### ISSUE THREAD

**Issue by tofsjonas** [mefechoel/svelte-navigator#77]
If I do this (like in the example here: [useResolve](https://github.com/mefechoel/svelte-navigator#useresolve)):

```jsx
<Route path="foo/*" component={SomeComponent} />
```

And then, inside SomeComponent:

```javascript
export let path: any
console.log(path)
```
I get this i the console:

```console
path undefined
```

**Comment by mefechoel** [comment]
The route component does not forward the path to its component children you can either pass anonther prop to the route and call it something other than `path` or render your component inside the routers slot and also pass it the path like so:

```html
<Route path="foo/*">
  <SomeComponent path="foo/*" />
</Route>
```
