### ISSUE TITLE
May be something incorrect in the private route example

### ISSUE THREAD

**Issue by mmrath** [mefechoel/svelte-navigator#8]
**Describe the bug**
I was looking at the private-routes example. Once you start the serve and navigate to `http://localhost:<port>/profile`, it does not render the login page, event though the url changes to `http://localhost:<port>/login`.

I moved code in `PrivateRouteGaurd` to `onMount` that appeared to work. But I am not sure if that is correct.

```
    onMount(checkUser);
    function checkUser() {
        if (!$user) {
            navigate("/login", {
                state: { from: $location.pathname },
                replace: true,
            });
        }
    }
```

**To Reproduce**
1. Go to `http://localhost:<port>/profile` once you start `private-routes` example

**Comment by mefechoel** [comment]
Hey @mmrath, I cannot reproduce the bug. I've tried the example in firefox and chrome and it works as expected.
Did you modify the example in any other way?

**Comment by mmrath** [comment]
@mefechoel I tried it again just now and it worked. Sorry for the noise, I must have done something wrong. 

Thanks for your work on this.
